// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmvoV_1IXaVeVt8K4r0q20bRBzP9sEods',
    appId: '1:101344698735:web:481b376f8927281330089a',
    messagingSenderId: '101344698735',
    projectId: 'garageeka-960e9',
    authDomain: 'garageeka-960e9.firebaseapp.com',
    storageBucket: 'garageeka-960e9.appspot.com',
    measurementId: 'G-SKP39C6G5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHzJWkkpJvV3aekkDHmxkCpBDcLGBpoY',
    appId: '1:101344698735:android:0a1e28a5fe07ba3130089a',
    messagingSenderId: '101344698735',
    projectId: 'garageeka-960e9',
    storageBucket: 'garageeka-960e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZEdK1ac94BV17MUCZES3NZcNwdAl8u4U',
    appId: '1:101344698735:ios:26890e40875d9fcf30089a',
    messagingSenderId: '101344698735',
    projectId: 'garageeka-960e9',
    storageBucket: 'garageeka-960e9.appspot.com',
    iosBundleId: 'com.example.musicBand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZEdK1ac94BV17MUCZES3NZcNwdAl8u4U',
    appId: '1:101344698735:ios:37e193e5450cb20030089a',
    messagingSenderId: '101344698735',
    projectId: 'garageeka-960e9',
    storageBucket: 'garageeka-960e9.appspot.com',
    iosBundleId: 'com.example.musicBand.RunnerTests',
  );
}
